# Generated by Django 5.1.3 on 2024-11-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(related_name='commandes', to='shop.product'),
        ),
    ]
